# Docker Compose file for running your virtual stock trading app
# This uses different ports to avoid conflicts with existing containers
services:

  # 1. The MySQL Database Service
  db:
    image: mysql:8.0
    container_name: vst-mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: vst_password_2024
      MYSQL_DATABASE: virtual_stock_trader
    ports:
      - "3307:3306"  # Using port 3307 to avoid conflicts
    volumes:
      - mysql-data:/var/lib/mysql

  # 2. The Spring Boot Backend Service
  backend:
    image: cavinsam/virtual-stock-trading-app-backend:latest
    container_name: vst-backend-app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8082:8081"  # Using port 8082 to avoid conflicts
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/virtual_stock_trader
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=vst_password_2024
      - JWT_SECRET=your_jwt_secret_key_here_change_in_production
      - ALPHAVANTAGE_API_KEY=your_alphavantage_api_key_here

  # 3. The React Frontend Service
  frontend:
    image: cavinsam/virtual-stock-trading-app-frontend:latest
    container_name: vst-frontend-app
    restart: unless-stopped
    ports:
      - "3000:80"  # Using port 3000 to avoid conflicts
    depends_on:
      - backend

volumes:
  mysql-data:
